"""Centralized default configuration for Task 1 pipeline scripts."""

IMAGE_DIR = "/scratch/users/agraillet/images"
OUTPUT_DIR = "outputs"

# Shared
TOPK_RESULTS_PATH = f"{OUTPUT_DIR}/topk_results.json"
EMBEDDINGS_PATH = f"{OUTPUT_DIR}/embeddings.pt"
VISUALIZATIONS_DIR = f"{OUTPUT_DIR}/visualizations"
METRICS_PATH = f"{OUTPUT_DIR}/metrics.json"
RETRIEVAL_EVAL_DETAILS_PATH = f"{OUTPUT_DIR}/retrieval_eval_details.json"

DISTANCE_THRESHOLD_M = 50.0
ANGLE_THRESHOLD_DEG = None

# task1.py defaults
TASK1_ANNOTATIONS_DB = "dataset/splits/annotations_train.json"
TASK1_ANNOTATIONS_QUERY = "dataset/splits/annotations_val.json"
TASK1_TOPK = 10
TASK1_OUTPUT = TOPK_RESULTS_PATH
TASK1_CHECKPOINT = None
TASK1_BATCH_SIZE = 32
TASK1_NUM_WORKERS = 4
TASK1_EMBEDDINGS_OUTPUT = EMBEDDINGS_PATH

# visualize_task1_results.py defaults
VIS_RESULTS = TOPK_RESULTS_PATH
VIS_EMBEDDINGS = EMBEDDINGS_PATH
VIS_OUTPUT_DIR = VISUALIZATIONS_DIR
VIS_QUERY_ID = None
VIS_MAX_QUERIES = 20
VIS_THRESHOLD_M = DISTANCE_THRESHOLD_M
VIS_ANGLE_THRESHOLD_DEG = ANGLE_THRESHOLD_DEG
VIS_TILE_SIZE = 300

# evaluate_task1_results.py defaults
EVAL_RESULTS = TOPK_RESULTS_PATH
EVAL_EMBEDDINGS = EMBEDDINGS_PATH
EVAL_OUTPUT = METRICS_PATH
EVAL_DETAILS_OUTPUT = RETRIEVAL_EVAL_DETAILS_PATH
EVAL_KS = [1, 5, 10]
EVAL_DISTANCE_THRESHOLD_M = DISTANCE_THRESHOLD_M
EVAL_ANGLE_THRESHOLD_DEG = ANGLE_THRESHOLD_DEG

# dataset/split_data.py defaults
SPLIT_INPUT_METADATA = f"{IMAGE_DIR}/metadata.json"
SPLIT_OUTPUT_DIR = "dataset/splits"
SPLIT_VAL_RATIO = 0.2
SPLIT_SEED = 42
